"""quality inspection and incoming batches and shipment items

Revision ID: 3b617c3fe6e7
Revises: 0042_report_unit_prescreen
Create Date: 2026-05-29 13:47:35.749107
"""

from alembic import op
import sqlalchemy as sa


revision = '3b617c3fe6e7'
down_revision = '0042_report_unit_prescreen'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), server_default='minor', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_defect_codes_code')
    )
    op.create_index(op.f('ix_defect_codes_tenant_id'), 'defect_codes', ['tenant_id'], unique=False)
    op.create_table('inspection_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_inspection_templates_code')
    )
    op.create_index(op.f('ix_inspection_templates_process_id'), 'inspection_templates', ['process_id'], unique=False)
    op.create_index(op.f('ix_inspection_templates_product_id'), 'inspection_templates', ['product_id'], unique=False)
    op.create_index(op.f('ix_inspection_templates_tenant_id'), 'inspection_templates', ['tenant_id'], unique=False)
    op.create_table('inspection_template_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('item_type', sa.String(length=16), server_default='pass_fail', nullable=False),
    sa.Column('standard_value', sa.String(length=64), nullable=True),
    sa.Column('upper_limit', sa.String(length=64), nullable=True),
    sa.Column('lower_limit', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'seq', name='uq_inspection_template_items_seq')
    )
    op.create_index(op.f('ix_inspection_template_items_template_id'), 'inspection_template_items', ['template_id'], unique=False)
    op.create_table('incoming_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_batches_batch_no'), 'incoming_batches', ['batch_no'], unique=False)
    op.create_index(op.f('ix_incoming_batches_material_id'), 'incoming_batches', ['material_id'], unique=False)
    op.create_index(op.f('ix_incoming_batches_purchase_order_id'), 'incoming_batches', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_incoming_batches_tenant_id'), 'incoming_batches', ['tenant_id'], unique=False)
    op.create_table('inspection_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('report_unit_audit_id', sa.Integer(), nullable=False),
    sa.Column('template_item_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=8), server_default='pass', nullable=False),
    sa.Column('measured_value', sa.String(length=64), nullable=True),
    sa.Column('defect_code_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['defect_code_id'], ['defect_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_unit_audit_id'], ['report_unit_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_item_id'], ['inspection_template_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_records_defect_code_id'), 'inspection_records', ['defect_code_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_report_unit_audit_id'), 'inspection_records', ['report_unit_audit_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_template_item_id'), 'inspection_records', ['template_item_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_tenant_id'), 'inspection_records', ['tenant_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'shipment_id', 'sku_id', name='uq_shipment_items_tenant_shipment_sku')
    )
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_sku_id'), 'shipment_items', ['sku_id'], unique=False)
    op.create_index(op.f('ix_shipment_items_tenant_id'), 'shipment_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_items_tenant_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_sku_id'), table_name='shipment_items')
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index(op.f('ix_inspection_records_tenant_id'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_template_item_id'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_report_unit_audit_id'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_defect_code_id'), table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_index(op.f('ix_incoming_batches_tenant_id'), table_name='incoming_batches')
    op.drop_index(op.f('ix_incoming_batches_purchase_order_id'), table_name='incoming_batches')
    op.drop_index(op.f('ix_incoming_batches_material_id'), table_name='incoming_batches')
    op.drop_index(op.f('ix_incoming_batches_batch_no'), table_name='incoming_batches')
    op.drop_table('incoming_batches')
    op.drop_index(op.f('ix_inspection_template_items_template_id'), table_name='inspection_template_items')
    op.drop_table('inspection_template_items')
    op.drop_index(op.f('ix_inspection_templates_tenant_id'), table_name='inspection_templates')
    op.drop_index(op.f('ix_inspection_templates_product_id'), table_name='inspection_templates')
    op.drop_index(op.f('ix_inspection_templates_process_id'), table_name='inspection_templates')
    op.drop_table('inspection_templates')
    op.drop_index(op.f('ix_defect_codes_tenant_id'), table_name='defect_codes')
    op.drop_table('defect_codes')
    # ### end Alembic commands ###

